---
- name: Update apt
  apt: update_cache=yes
  sudo: yes

- name: Install base packages
  apt: pkg=$item state=latest
  sudo: yes
  with_items:
    - git-core
    - build-essential
    - curl
    - python-psycopg2
    - postgresql
    - postgresql-client
    - libpq-dev
    - postgresql-contrib
    - nfs-common # make virtualbox faster
