---
- name: create db user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ db_user }} password=secret
                   role_attr_flags=CREATEDB,NOSUPERUSER
- name: create dbs
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=$item owner={{ db_user }}
                 encoding='UTF-8' lc_collate='en_US.UTF-8' lc_ctype='en_US.UTF-8' template='template0'
                 state=present
  with_items:
    - dev
    - test
